import { Appointment, AppointmentStatus, AppointmentPriority, AppointmentType } from '../types';

/**
 * Mock medical appointments data for testing and development
 * This represents the expected JSON response format from a medical API
 */
export const mockAppointments: Appointment[] = [
  {
    id: 'apt-001',
    title: 'Telemedicine Consultation',
    description: 'Online consultation for chest pain evaluation',
    startTime: '2024-01-15T09:00:00Z',
    endTime: '2024-01-15T10:00:00Z',
    status: AppointmentStatus.CONFIRMED,
    priority: AppointmentPriority.URGENT,
    type: AppointmentType.TELEMEDICINE,
    patientId: 'patient-001',
    patientName: 'María González',
    patientEmail: 'maria.gonzalez@email.com',
    patientPhone: '+1-555-0123',
    patientDateOfBirth: '1985-03-15T00:00:00Z',
    patientGender: 'female',
    doctorId: 'doctor-001',
    doctorName: 'Dr. Carlos Rodríguez',
    doctorSpecialty: 'Cardiology',
    location: 'Online - Telemedicine Platform',
    isOnlineAppointment: true,
    meetingLink: 'https://meet.medicalplatform.com/room-123',
    meetingPassword: 'MED123',
    symptoms: ['Chest pain', 'Shortness of breath', 'Fatigue'],
    diagnosis: 'Pending evaluation',
    notes: 'Patient reports chest pain for 2 days. No known allergies.',
    followUpRequired: true,
    followUpDate: '2024-01-22T09:00:00Z',
    insuranceProvider: 'Seguro Popular',
    insuranceNumber: 'SP123456789',
    copay: 0,
    createdAt: '2024-01-10T08:30:00Z',
    updatedAt: '2024-01-10T08:30:00Z',
    metadata: {
      department: 'Cardiology',
      referralSource: 'Emergency Room',
      previousAppointments: 3,
      lastVisit: '2023-11-15',
    },
  },
  {
    id: 'apt-002',
    title: 'Follow-up Consultation',
    description: 'Follow-up appointment for diabetes management',
    startTime: '2024-01-15T14:00:00Z',
    endTime: '2024-01-15T15:00:00Z',
    status: AppointmentStatus.SCHEDULED,
    priority: AppointmentPriority.ROUTINE,
    type: AppointmentType.FOLLOW_UP,
    patientId: 'patient-002',
    patientName: 'José Martínez',
    patientEmail: 'jose.martinez@email.com',
    patientPhone: '+1-555-0456',
    patientDateOfBirth: '1972-07-22T00:00:00Z',
    patientGender: 'male',
    doctorId: 'doctor-002',
    doctorName: 'Dra. Ana López',
    doctorSpecialty: 'Endocrinology',
    location: 'Hospital General - Consultorio 205',
    isOnlineAppointment: false,
    symptoms: ['High blood sugar', 'Increased thirst', 'Weight loss'],
    diagnosis: 'Type 2 Diabetes Mellitus',
    prescription: ['Metformin 500mg', 'Glipizide 5mg'],
    notes: 'Patient needs to monitor blood glucose levels daily. Diet counseling required.',
    followUpRequired: true,
    followUpDate: '2024-02-15T14:00:00Z',
    insuranceProvider: 'IMSS',
    insuranceNumber: 'IMSS987654321',
    copay: 50,
    createdAt: '2024-01-12T10:15:00Z',
    updatedAt: '2024-01-12T10:15:00Z',
    metadata: {
      department: 'Endocrinology',
      referralSource: 'Primary Care',
      previousAppointments: 5,
      lastVisit: '2023-12-15',
      labResults: ['HbA1c: 8.2%', 'Fasting Glucose: 180 mg/dL'],
    },
  },
  {
    id: 'apt-003',
    title: 'Lab Results Review',
    description: 'Review of blood work and imaging results',
    startTime: '2024-01-16T11:00:00Z',
    endTime: '2024-01-16T11:30:00Z',
    status: AppointmentStatus.SCHEDULED,
    priority: AppointmentPriority.ROUTINE,
    type: AppointmentType.LAB_RESULTS,
    patientId: 'patient-003',
    patientName: 'Carmen Herrera',
    patientEmail: 'carmen.herrera@email.com',
    patientPhone: '+1-555-0789',
    patientDateOfBirth: '1990-12-08T00:00:00Z',
    patientGender: 'female',
    doctorId: 'doctor-003',
    doctorName: 'Dr. Miguel Torres',
    doctorSpecialty: 'Internal Medicine',
    location: 'Online - Telemedicine Platform',
    isOnlineAppointment: true,
    meetingLink: 'https://meet.medicalplatform.com/room-456',
    meetingPassword: 'LAB789',
    symptoms: ['Fatigue', 'Weight gain'],
    diagnosis: 'Hypothyroidism',
    prescription: ['Levothyroxine 50mcg'],
    notes: 'Lab results show elevated TSH levels. Patient responds well to medication.',
    followUpRequired: true,
    followUpDate: '2024-03-16T11:00:00Z',
    insuranceProvider: 'Seguro Popular',
    insuranceNumber: 'SP456789123',
    copay: 0,
    createdAt: '2024-01-08T16:45:00Z',
    updatedAt: '2024-01-08T16:45:00Z',
    metadata: {
      department: 'Internal Medicine',
      referralSource: 'Annual Checkup',
      previousAppointments: 2,
      lastVisit: '2023-10-16',
      labResults: ['TSH: 8.5 mIU/L', 'Free T4: 0.8 ng/dL', 'CBC: Normal'],
    },
  },
  {
    id: 'apt-004',
    title: 'Emergency Consultation',
    description: 'Urgent consultation for severe headache',
    startTime: '2024-01-17T10:00:00Z',
    endTime: '2024-01-17T10:30:00Z',
    status: AppointmentStatus.IN_PROGRESS,
    priority: AppointmentPriority.EMERGENCY,
    type: AppointmentType.EMERGENCY,
    patientId: 'patient-004',
    patientName: 'Roberto Silva',
    patientEmail: 'roberto.silva@email.com',
    patientPhone: '+1-555-0321',
    patientDateOfBirth: '1988-05-12T00:00:00Z',
    patientGender: 'male',
    doctorId: 'doctor-004',
    doctorName: 'Dra. Patricia Morales',
    doctorSpecialty: 'Neurology',
    location: 'Hospital General - Sala de Emergencias',
    isOnlineAppointment: false,
    symptoms: ['Severe headache', 'Nausea', 'Photophobia', 'Neck stiffness'],
    diagnosis: 'Migraine with aura',
    prescription: ['Sumatriptan 50mg', 'Ibuprofen 400mg'],
    notes: 'Patient reports sudden onset of severe headache. No fever. Neurological exam normal.',
    followUpRequired: true,
    followUpDate: '2024-01-24T10:00:00Z',
    insuranceProvider: 'IMSS',
    insuranceNumber: 'IMSS123456789',
    copay: 0,
    createdAt: '2024-01-05T09:20:00Z',
    updatedAt: '2024-01-17T10:15:00Z',
    metadata: {
      department: 'Emergency Medicine',
      referralSource: 'Emergency Room',
      previousAppointments: 1,
      lastVisit: '2023-08-17',
      vitalSigns: ['BP: 140/90', 'HR: 85', 'Temp: 98.6°F'],
    },
  },
  {
    id: 'apt-005',
    title: 'Preventive Care Visit',
    description: 'Annual preventive care and health screening',
    startTime: '2024-01-18T18:00:00Z',
    endTime: '2024-01-18T19:00:00Z',
    status: AppointmentStatus.CANCELLED,
    priority: AppointmentPriority.ROUTINE,
    type: AppointmentType.PREVENTIVE_CARE,
    patientId: 'patient-005',
    patientName: 'Elena Vargas',
    patientEmail: 'elena.vargas@email.com',
    patientPhone: '+1-555-0654',
    patientDateOfBirth: '1975-09-30T00:00:00Z',
    patientGender: 'female',
    doctorId: 'doctor-005',
    doctorName: 'Dr. Fernando Ruiz',
    doctorSpecialty: 'Family Medicine',
    location: 'Centro de Salud Familiar',
    isOnlineAppointment: false,
    symptoms: [],
    diagnosis: 'Preventive care',
    notes: 'Cancelled by patient due to work emergency. Rescheduled for next week.',
    followUpRequired: true,
    followUpDate: '2024-01-25T18:00:00Z',
    insuranceProvider: 'Seguro Popular',
    insuranceNumber: 'SP789123456',
    copay: 0,
    createdAt: '2024-01-10T12:00:00Z',
    updatedAt: '2024-01-17T08:00:00Z',
    metadata: {
      department: 'Family Medicine',
      referralSource: 'Self-referred',
      previousAppointments: 8,
      lastVisit: '2023-01-18',
      screeningTests: ['Mammography', 'Pap Smear', 'Blood Pressure'],
    },
  },
  {
    id: 'apt-006',
    title: 'Prescription Renewal',
    description: 'Renewal of hypertension medication',
    startTime: '2024-01-19T15:00:00Z',
    endTime: '2024-01-19T15:30:00Z',
    status: AppointmentStatus.COMPLETED,
    priority: AppointmentPriority.ROUTINE,
    type: AppointmentType.PRESCRIPTION_RENEWAL,
    patientId: 'patient-006',
    patientName: 'Luis Mendoza',
    patientEmail: 'luis.mendoza@email.com',
    patientPhone: '+1-555-0987',
    patientDateOfBirth: '1965-04-14T00:00:00Z',
    patientGender: 'male',
    doctorId: 'doctor-006',
    doctorName: 'Dra. Isabel Castro',
    doctorSpecialty: 'Cardiology',
    location: 'Online - Telemedicine Platform',
    isOnlineAppointment: true,
    meetingLink: 'https://meet.medicalplatform.com/room-789',
    meetingPassword: 'RX123',
    symptoms: [],
    diagnosis: 'Essential Hypertension',
    prescription: ['Losartan 50mg', 'Hydrochlorothiazide 12.5mg'],
    notes: 'Patient reports good blood pressure control. Medication dosage maintained.',
    followUpRequired: true,
    followUpDate: '2024-04-19T15:00:00Z',
    insuranceProvider: 'IMSS',
    insuranceNumber: 'IMSS456789123',
    copay: 25,
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-19T15:30:00Z',
    metadata: {
      department: 'Cardiology',
      referralSource: 'Self-referred',
      previousAppointments: 12,
      lastVisit: '2023-10-19',
      bloodPressureReadings: ['Home BP: 125/80', 'Office BP: 130/85'],
    },
  },
  {
    id: 'apt-007',
    title: 'Specialist Referral Consultation',
    description: 'Referral to dermatologist for skin condition evaluation',
    startTime: '2024-01-20T08:00:00Z',
    endTime: '2024-01-20T09:00:00Z',
    status: AppointmentStatus.RESCHEDULED,
    priority: AppointmentPriority.ROUTINE,
    type: AppointmentType.SPECIALIST_REFERRAL,
    patientId: 'patient-007',
    patientName: 'Sofia Ramírez',
    patientEmail: 'sofia.ramirez@email.com',
    patientPhone: '+1-555-0123',
    patientDateOfBirth: '1992-11-25T00:00:00Z',
    patientGender: 'female',
    doctorId: 'doctor-007',
    doctorName: 'Dr. Alejandro Vega',
    doctorSpecialty: 'Dermatology',
    location: 'Hospital General - Consultorio Dermatología',
    isOnlineAppointment: false,
    symptoms: ['Skin rash', 'Itching', 'Red patches'],
    diagnosis: 'Atopic Dermatitis',
    prescription: ['Hydrocortisone cream 1%', 'Cetirizine 10mg'],
    notes: 'Rescheduled from original date due to doctor availability. Patient has history of eczema.',
    followUpRequired: true,
    followUpDate: '2024-01-27T08:00:00Z',
    insuranceProvider: 'Seguro Popular',
    insuranceNumber: 'SP321654987',
    copay: 0,
    createdAt: '2024-01-03T14:20:00Z',
    updatedAt: '2024-01-15T11:00:00Z',
    metadata: {
      department: 'Dermatology',
      referralSource: 'Primary Care',
      previousAppointments: 4,
      lastVisit: '2023-09-20',
      skinCondition: 'Chronic atopic dermatitis',
      allergyHistory: ['Nickel allergy', 'Latex sensitivity'],
    },
  },
];

/**
 * Mock API response format
 * This represents how the API would return appointment data
 */
export const mockApiResponse = {
  success: true,
  data: mockAppointments,
  message: 'Appointments retrieved successfully',
  pagination: {
    page: 1,
    limit: 10,
    total: mockAppointments.length,
    totalPages: 1,
  },
};
